export const BRANDS = {
  doggyWash: {
    id: "doggy-wash",
    name: "Doggy Wash",
    tagline: "Grooming & Spa Canino a Domicilio",
    description: "Cuidado profesional en la puerta de tu hogar. Higiene, corte y estética con equipo especializado.",
    color: "#0284c7",
    badge: "Servicio a Domicilio",
    slug: "/doggy-wash",
    whatsapp: "524775187491",
    jotformAgentUrl: "https://agent.jotform.com/019ca04a1f7e7a6a92321eceb3ba72e8ae01",
  },
  petsEternity: {
    id: "pets-eternity",
    name: "Pets Eternity",
    tagline: "Funeraria & Crematorio para Mascotas",
    description: "Despedidas dignas, amorosas y en paz. Atención cálida 24/7 en León y zona Bajío.",
    color: "#6b7280",
    badge: "Atención 24/7",
    slug: "https://petseternity.com.mx",
    isExternal: true,
  },
  petHotel: {
    id: "pet-hotel",
    name: "Pet Hotel",
    tagline: "Pensión y Hospedaje Campestre",
    description: "Libertad, socialización y confort en espacios seguros mientras estás fuera.",
    color: "#16a34a",
    badge: "Hospedaje Seguro",
    slug: "#",
    isExternal: false,
  },
  vetForPets: {
    id: "vet-for-pets",
    name: "Vet for Pets",
    tagline: "Clínica Veterinaria & Especialidades",
    description: "Medicina preventiva, cirugías y diagnóstico con especialistas calificados.",
    color: "#dc2626",
    badge: "Salud y Cuidado",
    slug: "#",
    isExternal: false,
  },
};